### ISSUE TITLE
NONCE shouldn't be a constant

### ISSUE THREAD

**Issue by alagos** [XeroAPI/xero-ruby-token-migration-script#3]
With 
```ruby
NONCE = SecureRandom.uuid
#...
oauth_params['oauth_nonce'] = NONCE
```
I'm getting randomly `The nonce value "xxx" has already been used` as described [in the docs](https://developer.xero.com/documentation/auth-and-limits/oauth-issues).
I've changed to `oauth_params['oauth_nonce'] = SecureRandom.uuid`, so it generates a new `oauth_nonce` for every request.

**Comment by SerKnight** [comment]
Thanks for your contrib 🥳
